name: lint
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "structurizr/cli"
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x /usr/local/structurizr-cli/structurizr.sh
      - name: validate omit
        run: |
          /usr/local/structurizr-cli/structurizr.sh validate -w omit.dsl
          /usr/local/structurizr-cli/structurizr.sh validate -w pubsub.dsl
          /usr/local/structurizr-cli/structurizr.sh validate -w cms.dsl
          /usr/local/structurizr-cli/structurizr.sh validate -w lambda.dsl
