name: lint
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "structurizr/cli"
    steps:
      - uses: actions/checkout@v3
      - name: validate omit
        run: |
          structurizr --help
