name: Lint Workspaces
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  list-workspaces:
    runs-on: ubuntu-latest   
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix=$(ls *.dsl | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        
  check:
    needs: list-workspaces
    runs-on: ubuntu-latest
    container:
      image: "structurizr/cli"  
    strategy:
        matrix:
            workspace: ${{ fromJson(needs.list-workspaces.outputs.matrix) }}    
    steps:
      - uses: actions/checkout@v3
      - name: prepare environment
        run: | 
          chmod +x /usr/local/structurizr-cli/structurizr.sh
          ln -s /usr/local/structurizr-cli/structurizr.sh /bin/structurizr
        
      - name: validate workspace ${{ matrix.workspace }}
        run: |
          structurizr validate -w ${{ matrix.workspace }}
